animal/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('create/', views.add, name='add'),
    path('<int:animal_id>/delete', views.delete, name='delete'),
    path('<int:animal_id>/', views.edit, name='edit'),
]

grafik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from animal import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),
                  path('accounts/', include('accounts.urls')),
                  path('animals/', include('animal.urls')),
                  path('orders/', include('orders.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.orders, name='orders'),
    path('add/', views.add_order, name='add_order'),
    path('getservices/<int:pk>', views.get_services, name='get_services'),
    path('getanimals/<int:pk>', views.get_animals, name='get_animals'),

]

orders/models.py
from django.contrib.auth.models import User
from django.db import models

from animal.models import Animal, AnimalType


# Create your models here.
class OrderStatus(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ServiceType(models.Model):
    name = models.CharField(max_length=255)
    animal_type = models.ForeignKey(AnimalType, on_delete=models.CASCADE)
    cost = models.DecimalField(decimal_places=2, max_digits=4, default=0)
    duration = models.DurationField()

    def __str__(self):
        return self.name


class Order(models.Model):
    service_id = models.ForeignKey(ServiceType, on_delete=models.CASCADE)
    status_id = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
    owner_id = models.ForeignKey(User, on_delete=models.CASCADE)
    animal_id = models.ForeignKey(Animal, on_delete=models.CASCADE)
    cost = models.DecimalField(decimal_places=2, max_digits=4)
    date_ordered = models.DateTimeField()
    length = models.DurationField()

    def __str__(self):
        return f'Zamówienie {self.id} złożone przez {self.owner_id.username}'

orders/forms.py
from django import forms

from .models import ServiceType, Order


class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#id_date_ordered'
        })
    )


class CreateServiceTypeForm(forms.ModelForm):
    class Meta:
        model = ServiceType
        fields = ['animal_type']
        labels = {'animal_type': 'Rodzaj zwierzaka'}


class CreateOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['service_id', 'animal_id', 'status_id', 'cost', 'date_ordered', 'length']

orders/views.py
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.http import JsonResponse
from django.shortcuts import render
from django.utils import timezone

from animal.models import Animal
from .forms import CreateServiceTypeForm, CreateOrderForm
from .models import ServiceType, Order


# Create your views here.
@login_required(login_url="/accounts/login")
def orders(request):
    ordered = Order.objects.filter(owner_id=request.user)
    return render(request, 'orders/orders.html', {'orders': ordered})


@login_required(login_url="/accounts/login")
def add_order(request):
    form = CreateServiceTypeForm()
    order = CreateOrderForm()
    if request.method == 'POST':
        created_order = CreateOrderForm(request.POST)
        if created_order.is_valid():
            new_order = created_order.save(commit=False)
            new_order.service_id = created_order.cleaned_data['service_id']
            new_order.owner_id = request.user
            new_order.cost = created_order.cleaned_data['cost']
            if created_order.cleaned_data['date_ordered'] < timezone.now() + timedelta(days=3):
                return render(request, 'orders/add_order.html',
                              {'form': form, 'order': created_order,
                               'errors': "Zlecenia należy składać z minimum 3 dniowym wyprzedzeniem."})
            new_order.date_ordered = created_order.cleaned_data['date_ordered']
            new_order.length = created_order.cleaned_data['length']
            new_order.animal_id = created_order.cleaned_data['animal_id']
            new_order.save()
            ordered = Order.objects.filter(owner_id=request.user)
            return render(request, 'orders/orders.html', {'orders': ordered})
        else:
            errors = 'Nie wszystkie pola są wypełnione'
            return render(request, 'orders/add_order.html', {'form': form, 'order': created_order, 'errors': errors})
    else:
        return render(request, 'orders/add_order.html', {'form': form, 'order': order})


@login_required(login_url="/accounts/login")
def get_services(request, pk):
    services = ServiceType.objects.filter(animal_type__id=pk)
    services_serialized = serialize('json', services)
    return JsonResponse(services_serialized, safe=False)


@login_required(login_url="/accounts/login")
def get_animals(request, pk):
    animals = Animal.objects.filter(owner__id=request.user.id, type__id=pk)
    animals_serialized = serialize('json', animals)
    return JsonResponse(animals_serialized, safe=False)

orders/templates/orders/add_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Dodaj zlecenie{% endblock %}
{% block styles %}
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
          integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous"/>


{% endblock %}
{% block navigation %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Grafik</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link disabled">Witaj: {{ request.user.get_full_name }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'password_change' %}">Zmiana hasła</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="javascript:{document.getElementById('logout').submit()}">Wyloguj</a>
                            <form id="logout" method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <input type="hidden"/>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Logowanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Rejestracja</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}
    {% if errors %}
        <div class="row justify-content-md-center">
            <div class="col-md-auto alert alert-danger">
                <strong>Wystąpił błąd. </strong> {{ errors }}
            </div>
        </div>

    {% endif %}

    <div class="container">
        <form method="post" action=".">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for field in form %}
                <div class="form-group {% if field.errors %} alert alert-danger{% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }} {% render_field field class="form-control" %}
                </div>
            {% endfor %}
            <div class="form-group">
                <label for="id_service_id">Rodzaj usługi:</label>
                <select name="service_id" class="form-control" required id="id_service_id">
                    <option value="0">Nie wybrano</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_animal_id">Nazwa zwierzaka:</label>
                <select name="animal_id" class="form-control" required id="id_animal_id">
                    <option value="0">Nie wybrano</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_cost">Cena:</label>
                <input type="number" class="form-control" name="cost" step="0.01" required id="id_cost"/>

            </div>
            <div class="form-group">
                <label for="id_status_id">Status:</label>
                <select name="status_id" class="form-control" required id="status_id">
                    <option value="1">Zaplanowano</option>
                </select>

            </div>
            <div class="form-group">
                <label for="id_date_ordered">Data i czas usługi:</label>
                <div class="input-group date" id="id_date_ordered" data-target-input="nearest">
                    <input name="date_ordered" type="text" class="form-control datetimepicker-input"
                           data-target="#id_date_ordered" data-toggle="datetimepicker" required/>
                    <div class="input-group-append" data-target="#id_date_ordered" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="id_length">Czas usługi:</label>
                <input type="text" name="length" required class="form-control" id="id_length"/>
            </div>
            <input class="btn btn-primary" type="submit" value="Złóż zamówienie "/>
        </form>
    </div>


{% endblock %}

{% block scripts %}
    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
            integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
    <script>

        $("select#id_animal_type").change(function () {
            const value = $("select#id_animal_type").val()
            console.log(value)
            $.ajax({
                url: '/orders/getservices/' + value,
                dataType: 'json',
                success: function (data) {
                    const values = JSON.parse(data);
                    console.log(values);
                    $('select#id_service_id').find('option').remove().end();
                    values.forEach(function (element, index) {
                        $('select#id_service_id').append($('<option>').text(element.fields.name).attr('value', element.pk));
                    });
                    const selected = $('select#id_service_id').val();
                    values.forEach(function (element) {
                        if (element.pk == selected) {
                            $('input#id_cost').val(element.fields.cost);
                            $('input#id_length').val(element.fields.duration);
                        }
                    });
                }
            });
            $.ajax({
                url: '/orders/getanimals/' + value,
                dataType: 'json',
                success: function (data) {
                    const values = JSON.parse(data);
                    console.log(values);
                    $('select#id_animal_id').find('option').remove().end();
                    values.forEach(function (element, index) {
                        $('select#id_animal_id').append($('<option>').text(element.fields.name).attr('value', element.pk));
                    });
                }
            });

        });

        $("select#id_service_id").change(function () {
            const value = $("select#id_animal_type").val()
             $.ajax({
                url: '/orders/getservices/' + value,
                dataType: 'json',
                success: function (data) {
                    const values = JSON.parse(data);
                    console.log(values);
                   {% comment %} $('select#id_service_id').find('option').remove().end();
                    values.forEach(function (element, index) {
                        $('select#id_service_id').append($('<option>').text(element.fields.name).attr('value', element.pk));
                    });{% endcomment %}
                    const selected = $('select#id_service_id').val();
                    values.forEach(function (element) {
                        if (element.pk == selected) {
                            $('input#id_cost').val(element.fields.cost);
                            $('input#id_length').val(element.fields.duration);
                        }
                    });
                }
            });
        });

        $(function () {
            $("#id_date_ordered").datetimepicker({
                format: 'MM/DD/YYYY HH:mm',
            });
        });
    </script>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Zlecenia{% endblock %}
{% block navigation %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Grafik</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link disabled">Witaj: {{ request.user.get_full_name }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'password_change' %}">Zmiana hasła</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="javascript:{document.getElementById('logout').submit()}">Wyloguj</a>
                            <form id="logout" method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <input type="hidden"/>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Logowanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Rejestracja</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}
    <div class="container pt-2">
        <div class="col-md-3 mb-3">
            <div class="card h-80">
                <div class="card-body">
                    <a href="{% url 'add_order' %}" class="text-decoration-none"><span class="oi oi-plus"></span> Złóż
                        zamówienie</a>
                </div>
            </div>
        </div>
        {% if orders %}
            <div class="row">
                <div class="col-12">
                    <h1>Złożone zamówienia:</h1>
                    <table class="table table-hover">
                        <thead>

                        </thead>
                        <tbody>
                        {% for row in orders %}
                            <tr>
                                <td>{{ row.animal_id.name }}</td>
                                <td>{{ row.service_id.name }}</td>
                                <td>{{ row.date_ordered }}</td>
                                <td>{{ row.cost }}</td>
                                <td>{{ row.status_id.name }}</td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        {% endif %}
    </div>


{% endblock %}